auto: true # automatically update your jekyll
server: false # runs a local server
paginate: 10 # pagination basted on number of posts
exclude: ["Gemfile", "Gemfile.lock", "README.md", 'sass', 'watch.sh', 'style.scss'] # files to exclude

# Setup
title:            El blog de Josu Antón
tagline:          blog de josu antón
url:              http://josuanton.me
baseurl:          /
author:
  name:           Josu Antón
  url:            https://twitter.com/josuaton
  email:          josuantonsanz@gmail.com