# Site settings
title: El blog de Josu
email: josuantonsanz@gmail.com
description: "Este es mi blog, espero ir publicando cosas en el, nada del otro mundo"
baseurl: "http://josuanton.me/"
url: "http://josuanton.me"
twitter_username: josuanton
github_username:  josuantonsanz
facebook_username:  Josu Antón Sanz

# Build settings
markdown: kramdown
permalink: pretty
paginate: 5
exclude: ["node_modules"]