# Site settings
title: Clean Blog
email: josuantonsanz@gmail.com
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: "/"
url: "http://josuanton.me"
twitter_username: josuanton
github_username:  josuantonsanz
facebook_username:  Josu Antón Sanz

# Build settings
markdown: kramdown
permalink: pretty
paginate: 5
exclude: ["node_modules"]